server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market?serverTimezone=GMT
    username: root
    password: fumushaScarecr0w!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/**/*.xml



